name: myFirstGithubAction

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: lint_check.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Unit Test
        run: ./gradlew test

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Usegradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant permissions to Gradle
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew clean build

      - name: Run Espresso tests
        run: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/


